import { Tabs, SimpleGrid, Paper, Text, Button, Select, Group, Stack, Box, Loader, Center, Modal, Title, Divider, ActionIcon, Tooltip, TextInput as MantineTextInput, ScrollArea, Table } from '@mantine/core';
import { IconPrinter, IconFileAnalytics, IconSchool, IconUsers, IconRefresh, IconEye, IconDownload, IconTrash, IconBook, IconBuilding, IconChartBar, IconFileTypePdf, IconCsv, IconSearch } from '@tabler/icons-react';
import { PageHeader } from '../components/common/PageHeader';
import { DataTable, type Column } from '../components/common/DataTable';
import { StatusBadge } from '../components/common/StatusBadge';
import { useState, useEffect } from 'react';
import { reportsService } from '../services/reportsService';
import type { LiveReportResult } from '../services/reportsService';
import { useForm } from '@mantine/form';
import type { ReportLog, ReportStats } from '../services/reportsService';
import { notifications } from '@mantine/notifications';
import { modals } from '@mantine/modals';
import { exportToCsv } from '../utils/exportUtils';

const columns = (onView: (report: ReportLog) => void, onDownload: (report: ReportLog) => void, onDelete: (report: ReportLog) => void, downloadingId: string | null): Column<ReportLog>[] => [
    { accessor: 'name', header: 'Report Name' },
    { accessor: 'generatedBy', header: 'Generated By' },
    {
        accessor: 'createdAt',
        header: 'Date',
        render: (item) => new Date(item.createdAt).toLocaleDateString()
    },
    {
        accessor: 'status',
        header: 'Status',
        render: (item) => <StatusBadge status={item.status} />
    },
    {
        accessor: 'actions',
        header: '',
        width: 160,
        render: (item) => (
            <Group gap={4}>
                <Tooltip label="View Report Summary">
                    <ActionIcon variant="subtle" color="blue" onClick={() => onView(item)}>
                        <IconEye size={18} />
                    </ActionIcon>
                </Tooltip>

                <Tooltip label="Download Official PDF">
                    <ActionIcon
                        variant="subtle"
                        color="red"
                        disabled={item.status !== 'Ready'}
                        loading={downloadingId === item.id}
                        onClick={() => onDownload(item)}
                    >
                        <IconDownload size={18} />
                    </ActionIcon>
                </Tooltip>

                <Tooltip label="Delete Report">
                    <ActionIcon
                        variant="subtle"
                        color="gray"
                        onClick={() => onDelete(item)}
                    >
                        <IconTrash size={18} />
                    </ActionIcon>
                </Tooltip>
            </Group>
        )
    }
];

// ─── Report catalogue ─────────────────────────────────────────────────────────
const REPORT_TYPES = [
    {
        group: 'Students', items: [
            { value: 'students', label: 'All Students', filters: ['classLevelId', 'status', 'gender', 'fromDate', 'toDate'] },
            { value: 'students-arrears', label: 'Students in Arrears', filters: ['classLevelId', 'minAmount'] },
            { value: 'late-arrivals', label: 'Late Arrivals', filters: ['classLevelId', 'fromDate', 'toDate'] },
            { value: 'gate-passes', label: 'Gate Passes', filters: ['classLevelId', 'fromDate', 'toDate'] },
            { value: 'student-attendance', label: 'Student Attendance', filters: ['sectionId', 'fromDate', 'toDate'] },
            { value: 'new-enrollments', label: 'New Enrollments', filters: ['fromDate', 'toDate'] },
        ]
    },
    {
        group: 'Staff', items: [
            { value: 'staff', label: 'All Staff', filters: ['department', 'designation', 'fromDate', 'toDate'] },
            { value: 'staff-by-dept', label: 'Staff by Department', filters: [] },
        ]
    },
    {
        group: 'Visitors', items: [
            { value: 'visitors', label: 'All Visitors', filters: ['status', 'fromDate', 'toDate', 'purpose'] },
            { value: 'current-visitors', label: 'Currently on Premises', filters: [] },
        ]
    },
    {
        group: 'Academic', items: [
            { value: 'classes', label: 'Classes & Sections', filters: [] },
            { value: 'subjects', label: 'Subjects List', filters: [] },
            { value: 'exam-results', label: 'Exam Results', filters: ['classLevelId', 'examId'] },
        ]
    },
    {
        group: 'Financial', items: [
            { value: 'fee-collection', label: 'Fee Collection Log', filters: ['fromDate', 'toDate', 'method'] },
            { value: 'revenue', label: 'Revenue by Period', filters: ['fromDate', 'toDate'] },
        ]
    },
    {
        group: 'Overview', items: [
            { value: 'overview', label: 'School Overview', filters: [] },
        ]
    },
] as const;

const ALL_REPORT_ITEMS = REPORT_TYPES.flatMap(g => g.items);

export default function Reports() {
    const [activeTab, setActiveTab] = useState<string | null>('live');
    const [search, setSearch] = useState('');
    const [history, setHistory] = useState<ReportLog[]>([]);
    const [stats, setStats] = useState<ReportStats | null>(null);
    const [loading, setLoading] = useState(true);
    const [generating, setGenerating] = useState(false);
    const [downloadingId, setDownloadingId] = useState<string | null>(null);
    const [selectedReport, setSelectedReport] = useState<ReportLog | null>(null);

    // ─── Live report state ───────────────────────────────────────────────────────
    const [selectedType, setSelectedType] = useState<string | null>(null);
    const [liveFilters, setLiveFilters] = useState<Record<string, string>>({});
    const [liveResult, setLiveResult] = useState<LiveReportResult | null>(null);
    const [liveLoading, setLiveLoading] = useState(false);
    const [liveDownloading, setLiveDownloading] = useState(false);

    const form = useForm({
        initialValues: {
            reportType: '',
            period: 'Last 30 Days',
        }
    });

    useEffect(() => {
        loadReports();
    }, []);

    const loadReports = async () => {
        setLoading(true);
        try {
            const [historyData, statsData] = await Promise.all([
                reportsService.getHistory(),
                reportsService.getStats()
            ]);
            setHistory(historyData);
            setStats(statsData);
        } catch (error) {
            notifications.show({ title: 'Error', message: 'Failed to load reports', color: 'red' });
        } finally {
            setLoading(false);
        }
    };

    const handleGenerate = async (values: typeof form.values) => {
        if (!values.reportType) {
            notifications.show({ title: 'Required', message: 'Please select a report type', color: 'orange' });
            return;
        }
        setGenerating(true);
        try {
            await reportsService.generateReport({ ...values, type: activeTab?.toUpperCase() });
            notifications.show({ title: 'Success', message: 'Report generated successfully', color: 'green' });
            loadReports();
        } catch {
            notifications.show({ title: 'Error', message: 'Failed to generate report', color: 'red' });
        } finally {
            setGenerating(false);
        }
    };

    // ─── Live report handlers ────────────────────────────────────────────────────
    const handleRunReport = async () => {
        if (!selectedType) return;
        setLiveLoading(true);
        try {
            const result = await reportsService.getReportData(selectedType, liveFilters);
            setLiveResult(result);
        } catch {
            notifications.show({ title: 'Error', message: 'Failed to fetch report data', color: 'red' });
        } finally {
            setLiveLoading(false);
        }
    };

    const handleExportLivePdf = async () => {
        if (!selectedType || !liveResult) return;
        setLiveDownloading(true);
        try {
            await reportsService.downloadReportDataPdf(selectedType, liveFilters, liveResult.title.replace(/\s+/g, '_'));
            notifications.show({ title: 'Success', message: 'PDF downloaded', color: 'green' });
        } catch {
            notifications.show({ title: 'Error', message: 'Failed to download PDF', color: 'red' });
        } finally {
            setLiveDownloading(false);
        }
    };

    const handleExportLiveCsv = () => {
        if (!liveResult) return;
        exportToCsv(liveResult.rows, liveResult.title.replace(/\s+/g, '_'));
        notifications.show({ title: 'Success', message: 'CSV exported', color: 'green' });
    };

    const handleDownloadPdf = async (report: ReportLog) => {
        setDownloadingId(report.id);
        try {
            await reportsService.downloadPdf(report.id, report.name.replace(/[^a-z0-9]/gi, '_').toLowerCase());
            notifications.show({ title: 'Success', message: 'Report downloaded successfully', color: 'green' });
        } catch (error) {
            notifications.show({ title: 'Error', message: 'Failed to download report', color: 'red' });
        } finally {
            setDownloadingId(null);
        }
    };

    const handleDelete = (report: ReportLog) => {
        modals.openConfirmModal({
            title: 'Delete Report',
            centered: true,
            children: (
                <Text size="sm">
                    Are you sure you want to permanently delete <strong>{report.name}</strong>? This action cannot be undone.
                </Text>
            ),
            labels: { confirm: 'Delete', cancel: 'Cancel' },
            confirmProps: { color: 'red' },
            onConfirm: async () => {
                try {
                    await reportsService.delete(report.id);
                    notifications.show({ title: 'Deleted', message: 'Report removed from history', color: 'green' });
                    loadReports();
                } catch (error) {
                    notifications.show({ title: 'Error', message: 'Failed to delete report', color: 'red' });
                }
            },
        });
    };

    const filteredData = history.filter(item =>
        (activeTab === 'all' || item.type.toLowerCase() === activeTab) &&
        (item.name.toLowerCase().includes(search.toLowerCase()))
    );

    // One helper to update a single filter key, stable across renders
    const setLiveFilter = (key: string, val: string) =>
        setLiveFilters(prev => ({ ...prev, [key]: val }));

    // Derive active filters list from selected report type
    const liveReportMeta = ALL_REPORT_ITEMS.find(r => r.value === selectedType);
    const liveActiveFilters: string[] = (liveReportMeta?.filters as unknown as string[]) ?? [];

    const ReportStats = () => (
        <SimpleGrid cols={{ base: 1, sm: 4 }} mb="lg">
            <Paper withBorder p="md" radius="md">
                <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Reports Generated</Text>
                <Text size="xl" fw={700}>{stats?.totalGenerated || 0}</Text>
            </Paper>
            <Paper withBorder p="md" radius="md">
                <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Downloads</Text>
                <Text size="xl" fw={700}>{stats?.downloads || 0}</Text>
            </Paper>
            <Paper withBorder p="md" radius="md">
                <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Pending</Text>
                <Text size="xl" fw={700} c="orange">{stats?.pending || 0}</Text>
            </Paper>
            <Paper withBorder p="md" radius="md">
                <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Storage Used</Text>
                <Text size="xl" fw={700} c="blue">{stats?.storageUsed || '0.0 GB'}</Text>
            </Paper>
        </SimpleGrid>
    );

    const ReportFilters = ({ type }: { type: string }) => (
        <Paper withBorder p="md" radius="md" mb="md" bg="gray.0">
            <Text fw={500} mb="xs">Generate {type} Report</Text>
            <form onSubmit={form.onSubmit(handleGenerate)}>
                <Group align="flex-end">
                    <Select
                        label="Report Type"
                        placeholder="Select report type"
                        required
                        data={
                            type === 'Financial' ? ['Fee Collection Summary', 'Unpaid Invoices (Defaulters)', 'Transaction Log', 'Fee Structure Breakdown'] :
                                type === 'Academic' ? ['Student Performance', 'Attendance Summary', 'Class Grade Master Sheet', 'Class Timetables'] :
                                    type === 'HR' ? ['Staff Directory', 'Department Roster', 'Subject Allocations', 'Staff Attendance Summary'] :
                                        type === 'Students' ? ['Student Directory', 'Class & Section Lists', 'New Admissions Log'] :
                                            type === 'Logistics' ? ['Visitor Log', 'Gate Pass Registry', 'Late Arrivals Report', 'Admission Inquiries'] :
                                                type === 'Library' ? ['Book Inventory', 'Overdue Circulations'] :
                                                    ['Custom Query', 'Audit Log', 'System Activity']
                        }
                        w={250}
                        {...form.getInputProps('reportType')}
                    />
                    <Select
                        label="Period"
                        placeholder="Select period"
                        data={['Last 7 Days', 'Last 30 Days', 'This Month', 'Last Month', 'Custom Range']}
                        w={200}
                        {...form.getInputProps('period')}
                    />
                    <Button
                        type="submit"
                        leftSection={<IconRefresh size={16} />}
                        loading={generating}
                    >
                        Generate
                    </Button>
                </Group>
            </form>
        </Paper>
    );

    return (
        <Box>
            <PageHeader
                title="Reports & Analytics"
                subtitle="Generate, view, and print system reports"
                actions={<Button leftSection={<IconPrinter size={16} />} onClick={() => window.print()} variant="light">Print Page</Button>}
            />

            {loading ? (
                <Center h={200}><Loader /></Center>
            ) : (
                <>
                    <ReportStats />

                    <Tabs value={activeTab} onChange={setActiveTab} radius="md" mb="lg">
                        <Tabs.List>
                            <Tabs.Tab value="live" leftSection={<IconChartBar size={16} />}
                                style={{ fontWeight: activeTab === 'live' ? 700 : undefined }}>
                                Live Reports
                            </Tabs.Tab>
                            <Tabs.Tab value="students" leftSection={<IconUsers size={16} />}>Students</Tabs.Tab>
                            <Tabs.Tab value="academic" leftSection={<IconSchool size={16} />}>Academic</Tabs.Tab>
                            <Tabs.Tab value="financial" leftSection={<IconFileAnalytics size={16} />}>Financial</Tabs.Tab>
                            <Tabs.Tab value="hr" leftSection={<IconUsers size={16} />}>HR & Staff</Tabs.Tab>
                            <Tabs.Tab value="logistics" leftSection={<IconBuilding size={16} />}>Logistics</Tabs.Tab>
                            <Tabs.Tab value="library" leftSection={<IconBook size={16} />}>Library</Tabs.Tab>
                        </Tabs.List>

                        {/* ── LIVE REPORTS ─────────────────────────────────── */}
                        <Tabs.Panel value="live" pt="md">
                            <Stack>
                                {/* Report type picker + dynamic filters */}
                                <Paper withBorder p="md" radius="md">
                                    <Text fw={600} mb="sm">Select Report Type</Text>
                                    <Group align="flex-end" wrap="wrap">
                                        <Select
                                            label="Report"
                                            placeholder="Choose a report…"
                                            data={REPORT_TYPES.map(g => ({ group: g.group, items: g.items.map(i => ({ value: i.value, label: i.label })) }))}
                                            value={selectedType}
                                            onChange={v => { setSelectedType(v); setLiveResult(null); setLiveFilters({}); }}
                                            w={280}
                                            searchable
                                        />

                                        {liveActiveFilters.includes('fromDate') && (
                                            <MantineTextInput
                                                label="From Date" type="date" w={160}
                                                value={liveFilters.fromDate || ''}
                                                onChange={e => setLiveFilter('fromDate', e.target.value)}
                                            />
                                        )}
                                        {liveActiveFilters.includes('toDate') && (
                                            <MantineTextInput
                                                label="To Date" type="date" w={160}
                                                value={liveFilters.toDate || ''}
                                                onChange={e => setLiveFilter('toDate', e.target.value)}
                                            />
                                        )}
                                        {liveActiveFilters.includes('status') && selectedType === 'visitors' && (
                                            <Select
                                                label="Status"
                                                data={[{ value: '', label: 'All' }, { value: 'IN', label: 'In' }, { value: 'OUT', label: 'Out' }]}
                                                value={liveFilters.status || ''}
                                                onChange={v => setLiveFilter('status', v || '')}
                                                w={120}
                                            />
                                        )}
                                        {liveActiveFilters.includes('status') && selectedType === 'students' && (
                                            <Select
                                                label="Status"
                                                data={[
                                                    { value: '', label: 'All Statuses' },
                                                    { value: 'ACTIVE', label: 'Active' },
                                                    { value: 'INACTIVE', label: 'Inactive' },
                                                    { value: 'SUSPENDED', label: 'Suspended' },
                                                    { value: 'GRADUATED', label: 'Graduated' },
                                                ]}
                                                value={liveFilters.status || ''}
                                                onChange={v => setLiveFilter('status', v || '')}
                                                w={160}
                                            />
                                        )}
                                        {liveActiveFilters.includes('gender') && (
                                            <Select
                                                label="Gender"
                                                data={[
                                                    { value: '', label: 'All Genders' },
                                                    { value: 'MALE', label: 'Male' },
                                                    { value: 'FEMALE', label: 'Female' },
                                                    { value: 'OTHER', label: 'Other' },
                                                ]}
                                                value={liveFilters.gender || ''}
                                                onChange={v => setLiveFilter('gender', v || '')}
                                                w={140}
                                            />
                                        )}
                                        {liveActiveFilters.includes('department') && (
                                            <Select
                                                label="Department"
                                                data={[
                                                    { value: '', label: 'All Departments' },
                                                    { value: 'Administration', label: 'Administration' },
                                                    { value: 'Science', label: 'Science' },
                                                    { value: 'Mathematics', label: 'Mathematics' },
                                                    { value: 'English', label: 'English' },
                                                    { value: 'Arts', label: 'Arts' },
                                                    { value: 'Sports', label: 'Sports' },
                                                    { value: 'IT', label: 'IT' },
                                                    { value: 'Finance', label: 'Finance' },
                                                ]}
                                                value={liveFilters.department || ''}
                                                onChange={v => setLiveFilter('department', v || '')}
                                                w={190}
                                            />
                                        )}
                                        {liveActiveFilters.includes('method') && (
                                            <Select
                                                label="Payment Method"
                                                data={[
                                                    { value: '', label: 'All Methods' },
                                                    { value: 'CASH', label: 'Cash' },
                                                    { value: 'CARD', label: 'Card' },
                                                    { value: 'BANK_TRANSFER', label: 'Bank Transfer' },
                                                    { value: 'MOBILE_MONEY', label: 'Mobile Money' },
                                                ]}
                                                value={liveFilters.method || ''}
                                                onChange={v => setLiveFilter('method', v || '')}
                                                w={180}
                                            />
                                        )}
                                        {liveActiveFilters.includes('purpose') && (
                                            <MantineTextInput
                                                label="Purpose (contains)"
                                                placeholder="e.g. Parent Meeting"
                                                value={liveFilters.purpose || ''}
                                                onChange={e => setLiveFilter('purpose', e.target.value)}
                                                w={200}
                                            />
                                        )}

                                        <Button
                                            leftSection={<IconSearch size={16} />}
                                            onClick={handleRunReport}
                                            loading={liveLoading}
                                            disabled={!selectedType}
                                            mt={24}
                                        >
                                            Run Report
                                        </Button>
                                    </Group>
                                </Paper>

                                {/* Results */}
                                {liveLoading && <Center py="xl"><Loader /></Center>}

                                {liveResult && !liveLoading && (
                                    <Paper withBorder radius="md" p="md">
                                        <Group justify="space-between" mb="md">
                                            <div>
                                                <Text fw={700} size="lg">{liveResult.title}</Text>
                                                <Text size="sm" c="dimmed">
                                                    {liveResult.totalRecords} record{liveResult.totalRecords !== 1 ? 's' : ''}
                                                </Text>
                                            </div>
                                            <Group gap="xs">
                                                <Button variant="light" leftSection={<IconCsv size={16} />} onClick={handleExportLiveCsv}>
                                                    Export CSV
                                                </Button>
                                                <Button variant="light" color="red" leftSection={<IconFileTypePdf size={16} />}
                                                    onClick={handleExportLivePdf} loading={liveDownloading}>
                                                    Export PDF
                                                </Button>
                                            </Group>
                                        </Group>

                                        <ScrollArea>
                                            <Table striped highlightOnHover withTableBorder withColumnBorders fz="sm">
                                                <Table.Thead>
                                                    <Table.Tr>
                                                        {liveResult.columns.map(col => (
                                                            <Table.Th key={col.key}>{col.header}</Table.Th>
                                                        ))}
                                                    </Table.Tr>
                                                </Table.Thead>
                                                <Table.Tbody>
                                                    {liveResult.rows.length === 0 ? (
                                                        <Table.Tr>
                                                            <Table.Td colSpan={liveResult.columns.length}>
                                                                <Text c="dimmed" ta="center" py="md">No records found.</Text>
                                                            </Table.Td>
                                                        </Table.Tr>
                                                    ) : liveResult.rows.map((row, i) => (
                                                        <Table.Tr key={i}>
                                                            {liveResult.columns.map(col => (
                                                                <Table.Td key={col.key}>{row[col.key] ?? '—'}</Table.Td>
                                                            ))}
                                                        </Table.Tr>
                                                    ))}
                                                </Table.Tbody>
                                            </Table>
                                        </ScrollArea>
                                    </Paper>
                                )}
                            </Stack>
                        </Tabs.Panel>

                        <Tabs.Panel value="students" pt="md">
                            <ReportFilters type="Students" />
                        </Tabs.Panel>
                        <Tabs.Panel value="academic" pt="md">
                            <ReportFilters type="Academic" />
                        </Tabs.Panel>
                        <Tabs.Panel value="financial" pt="md">
                            <ReportFilters type="Financial" />
                        </Tabs.Panel>
                        <Tabs.Panel value="hr" pt="md">
                            <ReportFilters type="HR" />
                        </Tabs.Panel>
                        <Tabs.Panel value="logistics" pt="md">
                            <ReportFilters type="Logistics" />
                        </Tabs.Panel>
                        <Tabs.Panel value="library" pt="md">
                            <ReportFilters type="Library" />
                        </Tabs.Panel>
                    </Tabs>

                    <div id="printable-area">
                        <DataTable
                            data={filteredData}
                            columns={columns(setSelectedReport, handleDownloadPdf, handleDelete, downloadingId)}
                            search={search}
                            onSearchChange={setSearch}
                        />
                    </div>
                </>
            )}

            <Modal
                opened={!!selectedReport}
                onClose={() => setSelectedReport(null)}
                title={<Title order={4}>{selectedReport?.name}</Title>}
                size="lg"
            >
                {selectedReport && (
                    <Stack>
                        <Group justify="space-between">
                            <div>
                                <Text size="sm" c="dimmed">Generated By</Text>
                                <Text fw={500}>{selectedReport.generatedBy}</Text>
                            </div>
                            <div>
                                <Text size="sm" c="dimmed">Date</Text>
                                <Text fw={500}>{new Date(selectedReport.createdAt).toLocaleString()}</Text>
                            </div>
                        </Group>

                        <Divider my="sm" label="Report Summary" labelPosition="center" />

                        {selectedReport.parameters?.summary ? (
                            <Stack gap="xs">
                                <Text size="sm"><b>Total Records processed:</b> {selectedReport.parameters.summary.totalRecords}</Text>
                                <Text size="sm"><b>Selected Period:</b> {selectedReport.parameters.summary.period}</Text>
                                <Paper withBorder p="md" radius="sm" bg="gray.0">
                                    <Stack gap="xs">
                                        {selectedReport.parameters.summary.sections.map((section: any, idx: number) => (
                                            <div key={idx}>
                                                <Text size="sm" fw={700}>{section.title}</Text>
                                                <Text size="sm">{section.details || section.value}</Text>
                                            </div>
                                        ))}
                                    </Stack>
                                </Paper>
                            </Stack>
                        ) : (
                            <Text c="dimmed" fs="italic">No detailed summary available for this report.</Text>
                        )}

                        <Group justify="flex-end" mt="xl">
                            <Button variant="outline" leftSection={<IconPrinter size={16} />} onClick={() => window.print()}>Print Summary</Button>
                            <Button
                                variant="light"
                                color="red"
                                leftSection={<IconDownload size={16} />}
                                loading={downloadingId === selectedReport.id}
                                onClick={() => handleDownloadPdf(selectedReport)}
                            >
                                Download Official PDF
                            </Button>
                        </Group>
                    </Stack>
                )}
            </Modal>
        </Box>
    );
}
