import { Tabs, SimpleGrid, Paper, Text, Button, Select, Group, Stack, Box } from '@mantine/core';
import { IconFileTypePdf, IconPrinter, IconFileAnalytics, IconSchool, IconUsers, IconSettings, IconRefresh } from '@tabler/icons-react';
import { PageHeader } from '../components/common/PageHeader';
import { DataTable, type Column } from '../components/common/DataTable';
import { StatusBadge } from '../components/common/StatusBadge';
import { useState } from 'react';

interface Report {
    id: string;
    name: string;
    type: string;
    generatedBy: string;
    date: string;
    status: string;
}

const mockData: Report[] = [
    { id: '1', name: 'Monthly Financial Summary', type: 'Financial', generatedBy: 'System', date: '2024-03-01', status: 'Ready' },
    { id: '2', name: 'Student Attendance Report', type: 'Academic', generatedBy: 'John Admin', date: '2024-03-01', status: 'Ready' },
    { id: '3', name: 'Q1 Expense Report', type: 'Financial', generatedBy: 'Sarah Finance', date: '2024-02-28', status: 'Processing' },
    { id: '4', name: 'Staff Payroll History', type: 'HR', generatedBy: 'System', date: '2024-02-28', status: 'Ready' },
    { id: '5', name: 'Class 10A Performance', type: 'Academic', generatedBy: 'Mrs. Davis', date: '2024-02-25', status: 'Ready' },
];

const columns: Column<Report>[] = [
    { accessor: 'name', header: 'Report Name' },
    { accessor: 'generatedBy', header: 'Generated By' },
    { accessor: 'date', header: 'Date' },
    {
        accessor: 'status',
        header: 'Status',
        render: (item) => <StatusBadge status={item.status} />
    },
    {
        accessor: 'actions',
        header: '',
        width: 140,
        render: (item) => (
            <Group gap={4}>
                <Button variant="subtle" size="xs" color="gray" disabled={item.status !== 'Ready'} onClick={() => window.print()}>
                    <IconPrinter size={16} />
                </Button>
                <Button variant="subtle" size="xs" color="red" disabled={item.status !== 'Ready'}>
                    <IconFileTypePdf size={16} />
                </Button>
            </Group>
        )
    }
];

export default function Reports() {
    const [activeTab, setActiveTab] = useState<string | null>('financial');
    const [search, setSearch] = useState('');

    const filteredData = mockData.filter(item =>
        (activeTab === 'all' || item.type.toLowerCase() === activeTab) &&
        (item.name.toLowerCase().includes(search.toLowerCase()))
    );

    const ReportStats = () => (
        <SimpleGrid cols={{ base: 1, sm: 4 }} mb="lg">
            <Paper withBorder p="md" radius="md">
                <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Reports Generated</Text>
                <Text size="xl" fw={700}>1,240</Text>
            </Paper>
            <Paper withBorder p="md" radius="md">
                <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Downloads</Text>
                <Text size="xl" fw={700}>856</Text>
            </Paper>
            <Paper withBorder p="md" radius="md">
                <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Pending</Text>
                <Text size="xl" fw={700} c="orange">5</Text>
            </Paper>
            <Paper withBorder p="md" radius="md">
                <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Storage Used</Text>
                <Text size="xl" fw={700} c="blue">4.2 GB</Text>
            </Paper>
        </SimpleGrid>
    );

    const ReportFilters = ({ type }: { type: string }) => (
        <Paper withBorder p="md" radius="md" mb="md" bg="gray.0">
            <Text fw={500} mb="xs">Generate {type} Report</Text>
            <Group align="flex-end">
                <Select
                    label="Report Type"
                    placeholder="Select report type"
                    data={
                        type === 'Financial' ? ['Fee Collection', 'Expense Summary', 'Payroll Report', 'Profit & Loss'] :
                            type === 'Academic' ? ['Student Performance', 'Attendance Summary', 'Class Grade Sheet'] :
                                type === 'HR' ? ['Staff Attendance', 'Payroll History', 'Leave Report'] :
                                    ['Custom Query', 'Audit Log', 'System Activity']
                    }
                    w={250}
                />
                <Select
                    label="Period"
                    placeholder="Select period"
                    data={['Last 7 Days', 'Last 30 Days', 'This Month', 'Last Month', 'Custom Range']}
                    w={200}
                />
                <Button leftSection={<IconRefresh size={16} />}>Generate</Button>
            </Group>
        </Paper>
    );

    return (
        <Box>
            <style type="text/css" media="print">
                {`
                @media print {
                    body * {
                        visibility: hidden;
                    }
                    #printable-area, #printable-area * {
                        visibility: visible;
                    }
                    #printable-area {
                        position: absolute;
                        left: 0;
                        top: 0;
                        width: 100%;
                    }
                    /* Hide UI elements */
                    button, input, .mantine-Tabs-list {
                        display: none !important;
                    }
                }
                `}
            </style>

            <PageHeader
                title="Reports & Analytics"
                subtitle="Generate, view, and print system reports"
                actions={<Button leftSection={<IconPrinter size={16} />} onClick={() => window.print()} variant="light">Print Page</Button>}
            />

            <ReportStats />

            <Tabs value={activeTab} onChange={setActiveTab} radius="md" mb="lg">
                <Tabs.List>
                    <Tabs.Tab value="financial" leftSection={<IconFileAnalytics size={16} />}>Financial</Tabs.Tab>
                    <Tabs.Tab value="academic" leftSection={<IconSchool size={16} />}>Academic</Tabs.Tab>
                    <Tabs.Tab value="hr" leftSection={<IconUsers size={16} />}>HR & Staff</Tabs.Tab>
                    <Tabs.Tab value="custom" leftSection={<IconSettings size={16} />}>Custom</Tabs.Tab>
                </Tabs.List>

                <Tabs.Panel value="financial" pt="md">
                    <ReportFilters type="Financial" />
                </Tabs.Panel>
                <Tabs.Panel value="academic" pt="md">
                    <ReportFilters type="Academic" />
                </Tabs.Panel>
                <Tabs.Panel value="hr" pt="md">
                    <ReportFilters type="HR" />
                </Tabs.Panel>
                <Tabs.Panel value="custom" pt="md">
                    <ReportFilters type="Custom" />
                </Tabs.Panel>
            </Tabs>

            <div id="printable-area">
                <DataTable
                    data={filteredData}
                    columns={columns}
                    search={search}
                    onSearchChange={setSearch}
                    pagination={{ total: 1, page: 1, onChange: () => { } }}
                />
            </div>
        </Box>
    );
}
