import { Button, SimpleGrid, Paper, Text, Group } from '@mantine/core';
import { IconDownload, IconFileTypePdf, IconFileTypeCsv, IconRefresh } from '@tabler/icons-react';
import { PageHeader } from '../components/common/PageHeader';
import { DataTable, type Column } from '../components/common/DataTable';
import { StatusBadge } from '../components/common/StatusBadge';
import { useState } from 'react';

interface Report {
    id: string;
    name: string;
    type: string;
    generatedBy: string;
    date: string;
    status: string;
}

const mockData: Report[] = [
    { id: '1', name: 'Monthly Financial Summary', type: 'Finance', generatedBy: 'System', date: '2024-03-01', status: 'Ready' },
    { id: '2', name: 'Student Attendance Report', type: 'Academic', generatedBy: 'John Admin', date: '2024-03-01', status: 'Ready' },
    { id: '3', name: 'Q1 Expense Report', type: 'Finance', generatedBy: 'Sarah Finance', date: '2024-02-28', status: 'Processing' },
    { id: '4', name: 'Staff Payroll History', type: 'HR', generatedBy: 'System', date: '2024-02-28', status: 'Ready' },
];

const columns: Column<Report>[] = [
    { accessor: 'name', header: 'Report Name' },
    { accessor: 'type', header: 'Type' },
    { accessor: 'generatedBy', header: 'Generated By' },
    { accessor: 'date', header: 'Date' },
    {
        accessor: 'status',
        header: 'Status',
        render: (item) => <StatusBadge status={item.status} />
    },
    {
        accessor: 'actions',
        header: '',
        width: 120,
        render: (item) => (
            <Group gap={4}>
                <Button variant="subtle" size="xs" color="red" disabled={item.status !== 'Ready'}>
                    <IconFileTypePdf size={16} />
                </Button>
                <Button variant="subtle" size="xs" color="green" disabled={item.status !== 'Ready'}>
                    <IconFileTypeCsv size={16} />
                </Button>
            </Group>
        )
    }
];

export default function Reports() {
    const [search, setSearch] = useState('');

    const filteredData = mockData.filter(item =>
        item.name.toLowerCase().includes(search.toLowerCase()) ||
        item.type.toLowerCase().includes(search.toLowerCase())
    );

    return (
        <>
            <PageHeader
                title="Reports & Analytics"
                subtitle="Generate and download system reports"
                actions={<Button leftSection={<IconRefresh size={16} />}>Generate New Report</Button>}
            />

            <SimpleGrid cols={{ base: 1, sm: 4 }} mb="lg">
                <Paper withBorder p="md" radius="md">
                    <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Reports Generated</Text>
                    <Text size="xl" fw={700}>1,240</Text>
                </Paper>
                <Paper withBorder p="md" radius="md">
                    <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Downloads</Text>
                    <Text size="xl" fw={700}>856</Text>
                </Paper>
                <Paper withBorder p="md" radius="md">
                    <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Pending</Text>
                    <Text size="xl" fw={700} c="orange">5</Text>
                </Paper>
                <Paper withBorder p="md" radius="md">
                    <Text size="xs" c="dimmed" tt="uppercase" fw={700}>Storage Used</Text>
                    <Text size="xl" fw={700} c="blue">4.2 GB</Text>
                </Paper>
            </SimpleGrid>

            <DataTable
                data={filteredData}
                columns={columns}
                search={search}
                onSearchChange={setSearch}
                pagination={{ total: 1, page: 1, onChange: () => { } }}
            />
        </>
    );
}
