import { Modal, Stack, Group, Text, Divider, Paper, Button, Title } from '@mantine/core';
import { IconPrinter, IconDownload } from '@tabler/icons-react';
import type { ReportLog } from '../../services/reportsService';

interface ReportDetailModalProps {
    report: ReportLog | null;
    onClose: () => void;
    onDownload: (report: ReportLog) => void;
    downloadingId: string | null;
}

export function ReportDetailModal({ report, onClose, onDownload, downloadingId }: ReportDetailModalProps) {
    return (
        <Modal
            opened={!!report}
            onClose={onClose}
            title={<Title order={4}>{report?.name}</Title>}
            size="lg"
        >
            {report && (
                <Stack>
                    <Group justify="space-between">
                        <div>
                            <Text size="sm" c="dimmed">Generated By</Text>
                            <Text fw={500}>{report.generatedBy}</Text>
                        </div>
                        <div>
                            <Text size="sm" c="dimmed">Date</Text>
                            <Text fw={500}>{new Date(report.createdAt).toLocaleString()}</Text>
                        </div>
                    </Group>

                    <Divider my="sm" label="Report Summary" labelPosition="center" />

                    {report.parameters?.summary ? (
                        <Stack gap="xs">
                            <Text size="sm"><b>Total Records processed:</b> {report.parameters.summary.totalRecords}</Text>
                            <Text size="sm"><b>Selected Period:</b> {report.parameters.summary.period}</Text>
                            <Paper withBorder p="md" radius="sm" bg="gray.0">
                                <Stack gap="xs">
                                    {report.parameters.summary.sections.map((section: any, idx: number) => (
                                        <div key={idx}>
                                            <Text size="sm" fw={700}>{section.title}</Text>
                                            <Text size="sm">{section.details || section.value}</Text>
                                        </div>
                                    ))}
                                </Stack>
                            </Paper>
                        </Stack>
                    ) : (
                        <Text c="dimmed" fs="italic">No detailed summary available for this report.</Text>
                    )}

                    <Group justify="flex-end" mt="xl">
                        <Button variant="outline" leftSection={<IconPrinter size={16} />} onClick={() => window.print()}>Print Summary</Button>
                        <Button
                            variant="light"
                            color="red"
                            leftSection={<IconDownload size={16} />}
                            loading={downloadingId === report.id}
                            onClick={() => onDownload(report)}
                        >
                            Download Official PDF
                        </Button>
                    </Group>
                </Stack>
            )}
        </Modal>
    );
}
